[#mfeature, reftext='7.2.4']
==== MovingFeature Object
A MovingFeature object in a MF-JSON Prism document is a JSON object to represent
a moving feature that is spatially and temporally bounded,
and its position (continuously) changes over time with the members as shown in <<mfeaturejson>>.

[#mfeaturejson, reftext='{example-caption} {counter:example-num}']
.Example {example-num}: Members of a MovingFeature object
[source, javascript]
{
  "type": "Feature", //(MANDATORY)
  "temporalGeometry": {...}, //(MANDATORY)
  "temporalProperties": [...], //(OPTIONAL)
  "crs" : {...}, //(DEFAULT)
  "trs" : {...}, //(DEFAULT)
  "time": [...], //(OPTIONAL)
  "bbox": [...], //(OPTIONAL)
  "geometry": {...},  //(OPTIONAL)
  "properties": {...} //(OPTIONAL)
}

 * A MovingFeature object has a mandatory member with the name `"type"` whose value is the `"Feature"` string.
[NOTE]
Due to the compatibility issue with GeoJSON, MF-JSON Prism uses the same keyword to abstract a moving feature.
If a GeoJSON document has no foreign member defined in this specification,
applications can interpret the data by the semantics of GeoJSON members and types.

* A MovingFeature object has a mandatory member with the name `"temporalGeometry"`
and its value is a TemporalGeometry object as defined above (see <<tgeometry>>).
* A MovingFeature object has an optional member with the name `"temporalProperties"`
as additional dynamic non-spatial attributes whose value varies over time.
The `"temporalProperties"` member has a TemporalProperties object as defined in <<tproperties>> or a JSON `null` value.
* A MovingFeature object has two default members with the name `"crs"` and `"trs"`
for representing its spatial and temporal coordinate reference system respectively.
The value of the `"crs"` and `"trs"` member is a CoordinateReferenceSystem (CRS) object (see <<crs>>).
If a MovingFeature object has no `"crs"` and `"trs"`,
the object refers to the default spatial and temporal CRS.
The value expression of spatial and temporal coordinates of `"temporalGeometry"` and `"temporalProperties"`
is obedient to these CRS objects.
* A MovingFeature object can optionally have a `"time"` member for the temporal coordinate range
to cover all of temporal geometries and temporal properties with a LifeSpan object (see <<time>>).
* A MovingFeature object can optionally have a `"bbox"` member for the spatial coordinate range
with a BoundingBox object (see <<bbox>>). It represents a spatial domain to cover
a temporal geometry or a collection of temporal geometries.
* A MovingFeature object has an optional member with the name `"geometry"` allowing a JSON `null` value,
as the same semantics of GeoJSON (see <<geometry>>).
* A MovingFeature object has an optional member with the name `"properties"` allowing a JSON `null` value,
as the same semantics of GeoJSON (see <<properties>>). The properties member is an object (i.e., any JSON object or a JSON `null` value).

[TIP]
The difference from `"temporalProperties"` is that a `"properties"` member represents static attributes
whose value is fixed for the life span of a moving feature.

include::requirements/requirement_feature.adoc[]

/////////
 *An instance of `"geometry"` is represented by its own local CRS as a default CRS*.
 If a Feature object has no `"crs"` or `"trs"` member,
 the default CRS objects shall apply to the Feature object.
 If there is no CRS object for a spatial or temporal coordinate,
 a Feature object SHALL explicitly has `"crs"` or `"trs"` member with a JSON `null` value.
/////////
