[big]*i.     Abstract*

This standard defines how to encode and share the various movements of geographic features by using JavaScript Object Notation (JSON).
It provides an alternative encoding for OGC Moving Features instead of http://www.opengeospatial.org/standards/movingfeatures[XML Core [OGC 14-083r2]] and http://www.opengeospatial.org/standards/movingfeatures[Simple CSV [OGC 14-084r2]].
A moving feature, typically like a vehicle and pedestrian, contains a temporal geometry
whose location continuously changes over time and dynamic non-spatial attributes whose values vary with time.
This Moving Features JSON encoding defines a set of keywords to implement the conceptual schema of moving features defined in ISO 19141:2008 [ISO 19141:2008], accompanied with https://www.ietf.org/rfc/rfc7946.txt[IETF GeoJSON Format [IETF RFC 7946]].

////
In addition, this document provides an example of RESTful approaches as a OGC Web Feature Service that has the potential for simplicity, scalability, and resilience with respect to exchange of moving feature data across the Web.
////

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, moving features, encoding, JSON

[big]*iii.   Preface*
////
[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
====
////

This document specifies JSON encodings for the implementation of the conceptual schema of moving features defined in https://www.iso.org/standard/41445.html[ISO 19141:2008],
i.e., features whose locations change over time. OGC Moving Features Encoding standards http://www.opengeospatial.org/standards/movingfeatures[XML Core [OGC 14-083r2]]
and http://www.opengeospatial.org/standards/movingfeatures[Simple CSV [OGC 14-084r2]] have focused on the movement of 0-dimensional geometric primitives (Points),
called trajectories. In addition, the ISO schema excludes deformation and changes of non-spatial attributes of the feature.
However, there are requirements to represent and share the movements of 1-dimensional curve LineStrings, 2-dimensional surface Polygons, and 3-dimensional solid polyhedrons with time-varying non-spatial attributes in various application areas, including: Location Based Services, Intelligent Transportation Systems,
Disaster Risk Management Systems, and Smart City Applications. For example, the traffic congestion on roads and the hotspot of air pollution are typical moving features in the real world.

Therefore, OGC Moving Features JSON encodings (MF-JSON) define data members for one-parameter geometries and properties of the moving feature in time not only trajectory.
MF-JSON is compatible with the https://www.ietf.org/rfc/rfc7946.txt[IETF GeoJSON Format [IETF RFC 7946]].

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[big]*iv.    Submitting organizations*

The following organization has submitted this Document to the Open GeoSpatial Consortium, Inc.:

* Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology
* Defense Systems Company, Hitachi, Ltd.
* Pusan National University

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

{set:cellbgcolor!}
[width="99%", cols="3,7"]
|===========================================================
|*Name*          |*Organization*
|Kyoung-Sook KIM  |Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology
|Taehoon KIM  |Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology
|Nobuhiro ISHIMARU|Defense Systems Company, Hitachi, Ltd.
|Ki-Joune LI|Pusan National University
|===========================================================
