== The MF-JSON Format (Normative)

This standard specifies describe the structure and content of JSON (JavaScript Object Notation) [https://www.ietf.org/rfc/rfc7159.txt[IETF RFC7159]]
encoding implementation of the conceptual model for moving features described in http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=41445[ISO 19141:2008].
The MF-JSON format is based on GeoJSON https://www.ietf.org/rfc/rfc7946.txt[IETF RFC 7946] and defines new members to describe two types of dynamic attribute of a feature
or feature collection in a JSON document.

[WARNING]
.GeoJSON type
In IETF GeoJSON format, types are not extensible.
GeoJSON allows only the fixed types: FeatureCollection, Feature, Point, LineString, MultiPoint, Polygon, MultiLineString, MultiPolygon, and GeometryCollection.
MF-JSON is obedient to the GeoJSON rule not to occur contravention, and new types defined in this standard are only valid within "foreign members" of GeoJSON.

A MF-JSON document may contain instances that has one of the following types, as well as primitives types of JSON null, boolean, array, number, and string.

 * Moving feature object (see <<feature>>)
 * Moving feature collection object (see <<fcollection>>)
 * Coordinate reference system (CRS) object (see <<crs>>)
 * Temporal geometry object (see <<tgeometry>>)
 * Geometry object (see <<geometry>>)
 * Temporal properties object (see <<tproperties>>)
 * Interpolation object (see <<interpoation>>)
 * Life span (see <<time>>)
 * Bounding box (see <<bbox>>)
 * Properties object (see <<properties>>)


[NOTE]
The object in this document is a JSON object.
A JSON object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.
If the value of a member of an object is a JSON `null` value or a *default* value defined in this specification,
the member and its value can be omitted in the document.
If an object member is mandatory, its value does NOT allow a JSON `null` value. An optional member can have a JSON `null` value or be excluded from the document.

=== Requirements Class: Core
The core requirements every implementation of the MF-JSON data model must fulfill are listed in Table 1. Their normative definitions are given in the sequent subclauses.

include::requirements/requirements_class.adoc[]


[#feature, reftext='7.2. Feature Object']
=== Feature Object
MF-JSON comprises the types Feature and FeatureCollection to represent a feature (abstraction of real world phenomena) as same as GeoJSON,
but there are a dyamic feature in time.
A Feature object in a MF-JSON document represents a moving feature that is spatially bounded and its postion continously changes over time.

 * A Feature object SHALL have a `"type"` member with the value `"Feature"`.
[NOTE]
Due to the compatibility issue, MF-JSON uses the same keyword to abstract a moving feature.
If there is no member of temporal gemetry, applications can interprete the data by the semantics of GeoJSON members and types.
 * A Feature object SHALL have a member with the name `"temporalGeometry"`.  The value of the `"temporalGeometry"` member SHALL be a TemporalGeometry object as defined below (see <<tgeometry>>).
 It does NOT allow a JSON `null` value.
 * A Feature object has a a member with the name `"geometry"` as the base representation of a rigid geometry of the feature at a given reference time
 or a JSON `null` value. A rigid geometry, using a local origin and local ordinate vectors, may undergo translation or rotation,
 but remains congruent with its base representation. The value expression of the `"geometry"` member is the same as the `"geometry"` member of GeoJSON.
 * A Feature object has a `"bbox"` member for the spatial coordinate range and a `"time"` member for the temporal coordinate range of the life span to cover the moving feature.
 Two members of `"bbox"` and `"time"` allows a JSON `null` value.
 * A Feature object has a member with the name `"temporalProperties"` as additional thematic attributes whose value varies over time.
 The `"temporalProperties"` member has a JSON array of TemporalProperties objects as defined below or a JSON `null` value.
 * A Feature object has a member with the name `"properties"` as the same semantics of GeoJSON. The value of the properties member is an object
 (any JSON object or a JSON `null` value). The difference from `"temporalProperties"` is that a "properties" member has a static value during the life span of a feature.
 * A Feature object has a `"crs"` member for representing the spatial coordinate reference system and a `"trs"` member for the temporal coordinate reference system of a moving feature.
 The value of the `"crs"` and `"trs"` member is a CoordinateReferenceSystem (CRS) object, a default CRS, or a JSON `null` value (see <<crs>>).
 The value expression of spatial and temporal coordinates of `"temporalGeometry"`, `"temporalProperties"`, `"bbox"`, and `"time"` is obedient to
 these CRS objects. *An instance of `"geometry"` is represented by its own local CRS as a default CRS*.
 If a Feature object has no `"crs"` or `"trs"` member, the default CRS object shall apply to the Feature object.
 If there is no CRS object for a spatial or temporal coordinate, a Feature object SHALL explicitly has `"crs"` or `"trs"` member with a JSON `null` value.


include::requirements/requirement1.adoc[]

[source, javascript]
.Example {counter:example-num}: Members of a moving feature
{
    "type": "Feature", //(mandatory)
    "geometry": {...}, //(optional)
    "properties": {...}, //(optional)
    "crs" : {...}, //(default)
    "bbox": [...], //(optional)
    "temporalGeometry": {...}, //(mandatory)
    "temporalProperties": [...], //(optional)
    "trs" : {...}, //(default)
    "time": ... //(optional)
}

[#fcollection, reftext='7.3. FeatureCollection Object']
=== FeatureCollection Object
A MF-JSON object with the type "FeatureCollection" is a FeatureCollection object having a member with the name `"features"` of a collection of moving features.
The value of `"features"` is a JSON array. Each element of the array is a Feature object as defined above.

 * A FeatureCollection object SHALL have a `"type"` member with the value `"FeatureCollection"`.
 * A FeatureCollection object has a `"name"` member as a JSON string to indicate an alias of the collection. It allows a JSON `null` value.
 * A FeatureCollection object has a `"features"` member as a JSON array of Feature instances. It is possible for this array to be empty.
 * A FeatureCollection object has a `"bbox"`  member for the spatial coordinate range and a `"time"` member for the temporal coordinate range of the life span to cover
 all element instances of the collection. The values of `"bbox"` and `"time"` refer to the CRS objects of `"crs"` and `"trs"` below.
 * A FeatureCollection object has a `"crs"` and `"trs"` member like a Feature object.
 If a collection object has the value of the `"crs"` or `"trs"` member, its elements of `"features"` SHALL refer to the coordinate reference systems of the collection object,
 not features' reference systems. The `"crs"` and `"trs"` member is on the top-level object in a hierarchy of feature collection, feature, tempral geometry/temporal properies order.

include::requirements/requirement2.adoc[]

[source, javascript]
.Example {counter:example-num}: Members of a collection of moving features
{
    "type": "FeatureCollection", //(mandatory)
    "name": "...", //(optional)
    "features": [...], //(mandatory)
    "crs" : {...}, //(default)
    "bbox": [...], //(optional)
    "trs" : {...}, //(default)
    "time": [...] //(optional)
}


[#crs, reftext='7.4. CoordinateReferenceSystem Object']
=== CoordinateReferenceSystem Object
A coordinate reference system is usually comprised of two components: one coordinate system and one datum (reference frame).
The IETF GeoJSON format recommends that the coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system,
using the World Geodetic System 1984 (WGS 84)<<4>> datum, with longitude and latitude units of decimal degrees.
This is equivalent to the coordinate reference system identified by the http://spatialreference.org/ref/epsg/wgs-84[EPSG:4326] with the axis Lat-Long.
For a 3D coordinate with a altitude/elevation value, the value refers to distance above mean sea level (MSL or AMSL).
However, a moving feature needs a temporal coordinate system and may require an engineering coordinate reference system or parametric coordinate reference system
to represent the movement of the geometry of the feature in the case of an application request.
Therefore, MF-JSON allows the "crs" member of a Feature object to describe an alternative coordinate reference system
whose representation follows the way as described in GeoJSON(2008) and the “trs” member to describe a temporal coordinate reference system against which time is measured.
https://www.iso.org/iso-8601-date-and-time-format.html[ISO 8601] specifies the use of the Gregorian Calendar and 24 hour local or Coordinated Universal Time (UTC)
for information interchange. This shall be the primary temporal reference system for use with geographic information.

The vlaue of a `"crs"` and `"trs"` member

 * A non-null CoordinateReferenceSystem (CRS) object represents a coordinate reference system to which the postions of a moving feature are referenced.
 The value of a `"trs"` member SHALL is an CRS object that indicates a temporal coordinate reference system.
 * A non-null CRS object has two mandatory members: `"type"` and `"properties"`.
 * The value of the `"type"` member SHALL be a string as one of the string "name" and "link", indicating the type of CRS object.
 * The value of the `"properties"` member is a JSON object with members named `"name"`, `"href"`, and `"type"` whose value is a string or JSON `null` value.
 * CRS shall not change coordinate ordering.

==== Named CRS
A Named CRS object indicates a coordinate reference system by name.
In this case, the value of its "type" member must be the string "name".
The value of its "properties" member is an object containing a "name" member whose value is a string identifying a coordinate reference system (not JSON `null` value).
The value of `"href"` and `"type"` is a JSON `null` value.

[source, javascript]
.Example {counter:example-num}: Example of a named CRS object
{
    "type": "name",
    "properties": {
        "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
}

==== Linked CRS

A linked CRS object has one required member: "href", and one optional member: "type".
The value of the required "href" member must be a dereferenceable URI.
The value of the optional "type" member must be a string that hints at the format used to represent CRS parameters at the provided URI.
Suggested values are: "proj4", "ogcwkt", "esriwkt", but others can be used.

[source, javascript]
.Example {counter:example-num}: Example of a linked CRS object
{
    "type": "link",
    "properties": {
        "href": "http://example.com/crs/42",
        "type": "proj4"
    }
}

Relative links may be used to direct processors to CRS parameters in an auxiliary file::

[source, javascript]
.Example {counter:example-num}: Example of a linked CRS object
{
    "type": "link",
    "properties": {
        "href": "data.crs",
        "type": "ogcwkt"
    }
}

[#defaultCRS]
==== Default CRS

MF-JSON has two default CRS objects as follows:

 * http://www.opengis.net/def/crs/OGC/1.3/CRS84[WGS 84] with longitude and latitude units of decimal degrees: This CRS object is the default value of the `"crs"` member.

[source, javascript]
-----
    "crs" : {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        }
    }
-----

 * http://www.iso.org/iso/home/standards/iso8601.htm[ISO 8601] of dates and times using the Gregorian calendar: This CRS object is the default value of the `"trs"` member.

[source, javascript]
-----
    "trs" : {
        "type": "name",
        "properties": {
            "name": "urn:ogc:data:time:iso8601"
        }
    }
-----


[#tgeometry, reftext='7.5. TemporalGeometry Object']
=== TemporalGeometry Object
A moving feature, Feature object, has only one `"temporalGeometry"` member with a TemporalGeometry object to represent the movement of a moving feature,
i.e., changes of the position. A prism of the set of leaves (MF_PrismGeometry in ISO 19141) or trajectories (MF_TemporalTrajectory in ISO 19141) is realized by
a TemporalGeometry object modeled as a mapping function from latexmath:[t\in time] to a geometric object latexmath:[g] of Point, LineString, Polygon, MultiPoint,
MultiLineString, MultiPolygon, or GeometryCollection.

* A TemporalGeometry object SHALL have a `"type"` member with of of the value of `"MovingPoint"`, `"MovingLineString"`, `"MovingPolygon"`, `"MovingPointCloud"`,
`"MultiMovingPoint"`, `"MultiMovingLineString"`, `"MultiMovingPolygon"`, and `"MovingGeometryCollection"`. Depending on the value of `"type"`, a TemporalGeometry object
is classified into two object types: TemporalPrimitiveGeometry and TemporalAggregateGeometry.
** *MovingPoint*: The type represents a trajectory of a time-parametered 0-dimensional geometric primitive (Point),
representing a single position at a time position (instant) within its temporal domain.
Intuitively a temporal geometry of this type depicts a curve in a spatiotemporal domain.
It is used to express mf:AbstractTrajectory in the OGC® Moving Features standard.
For example, the movement information of people, vehicles, or hurricanes can be shared as a TemporalGeometry object with the `"MovingPoint"` type.
** *MovingLineString*: The type represents the prism of a time-parametered 1-dimensional (1D) geometric primitive (LineString),
whose leaf geometry at a time position is 1-dimensional linear object in a particular time period.
Intuitively a temporal geometry of this type depicts a set of surfaces in a spatiotemporal domain.
For example, the movement information of weather fronts or traffic congestion on roads can be shared as a TemporalGeometry object with the `"MovingLineString"` type.
** *MovingPolygon*: This type represents the prism of a time-parametered 2-dimensional (2D) geometric primitive (Polygon),
whose leaf geometry at a time position is 2-dimensional polygonal object in a particular time period.
Intuitively a temporal geometry of this type depicts a set of polyhedrons that are the convex hulls of two congruent polygons in a spatiotemporal domain.
For example, the changes of flooding areas or the movement information of air pollution can be shared as a TemporalGeometry object with the `"MovingPolygon"` type.
** *MovingPointCloud*: This type represents the prism of a time-parametered point aggregate whose leaf geometry at a time position is a set of points in a particular time period.
Intuitively a temporal geometry of this type depicts a set of curves in a spatiotemporal domain.
For example, the tacking information by using Light Detection and Ranging (LiDAR) can be shared as a TemporalGeometry object with the `"MovingPointCloud"` type.
** *MultiMovingPoint*: This type represents a set of temporal geometries whose type is `"MovingPoint"`.
** *MultiMovingLineString*: This type represents a set of temporal geometries whose type is `"MovingLineString"`.
** *MultiMovingPolygon*: This type represents a set of temporal geometries whose type is `"MovingPolygon"`.
** *MovingGeometryCollection*: It represents a collection of temporal geometries. Each temporal geometry in this array belongs to one of the above types.
* A TemporalGeometry object optionally has a `"crs"` and `"trs"` member.
If an object has no `"crs"` and `"trs"` member, then it may acquire the CRS instances of `"crs"` and `"trs"` member from upper-level braces of a JSON object.
If no CRS instance can be so acquired, the default CRSs shall apply to the object.


[#tprimitive, reftext='7.5. TemporalPrimitiveGeometry Object']
==== TemporalPrimitiveGeometry Object
When a TemporalGeometry object has a `"type"` member with of of the value of `"MovingPoint"`, `"MovingLineString"`, `"MovingPolygon"`, and `"MovingPointCloud"`,
the object SHALL be a TemporalPrimitiveGeometry object with additional memebers named `"coordinates"`, `"datetimes"`, `"orientations"`, and `"interpolation"`.

[source, javascript]
{
    "type": "MovingPoint | MovingLineString | MovingPolygon",  // (MANDATORY) vbar | as a means to select ONE type.
    "coordinates": [...],   //(MANDATORY)
    "datetimes" : [...],    //(MANDATORY)
    "orientations": [...], //(OPTIONAL)
    "interpolation": [...], //(MANDATORY)
    "trs": {}, //(OPTIONAL)
    "crs": {}  //(OPTIONAL)
}

* `"coordinates"`: The `"coordinates"` member is mandatory. Its value is a JSON array of leaf geometries of a temporal geometry, having at least one element. It does NOT allows a JSON `null` vlaue.
+
[width="99%", cols="1,^6,3", options="header"]
|=========
| Types   |      Formats of the `"coordinates"` value  |  _Comments_
| MovingPoint | [ [x1,y1(,z1)], [x2,y2(,z2)], ... ] | _a list of single positions to construct a point as each leaf at a time instant, increasing time order_
| MovingLineString | [ [[x11,y11(,z11)], [x12,y12(,z12)], ...], [[x21,y21(,z21)], [x22,y22(,z22)], ...], ... ] | _a list of LineString coordinate arrays to construct a linestring as each leaf at a time instant, increasing time order_
| MovingPolygon | [ [[[ox11,oy11(,oz11)], [ox12,oy12(,oz12)], ...], [[ix11,iy11(,iz11)],[ix12,iy12(,iz12)], ...],...], [[[ox21,oy21(,oz21)], [ox22,oy22(,oz22)], ...], [[ix21,iy21(,iz21)],[ix22,iy22(,iz22)], ...], ...], ... ] |  _a list of Polygon
coordinate arrays to construct a polygon as each leaf at a time instant, increasing time order_
| MovingPointCloud | [ [[x11,y11(,z11)], [x12,y12(,z12)], ...], [[x21,y21(,z21)], [x22,y22(,z22)], ...], ... ] | _a list of MultiPoint coordinate arrays to construct a set of points as each leaf at a time instant, increasing time order_
|=========

[NOTE]
==========
* A single position is represented by a JSON array of numbers,
which must contain two or more elements. The first two elements are longitude/easting (x) and latitude/northing (y), precisely in that order and using decimal numbers.
altitude/elevation (z) MAY be included as an optional third element.
* A LineString coordinate array is expressed as a JSON array of two or more positions.
* A Polygon coordinate array is expressed as a JSON array of LinearRing coordinate arrays. A LinearRing is closed LineString with 4 or more positions. The first and last
positions are equivalent (they represent equivalent points). For Polygons with multiple rings, the first must be the exterior ring and any others must be interior rings or holes.
* A MultiPoint coordinate array is a JSON array of single positions.
==========

* `"datetimes"`: The `"datetimes"` member is mandatory. Its value is a JSON array of instants of time to construct leaf geometries based on the temporal coordinate reference system
described by a CRS object of the `"trs"` member. The array SHALL be a list of monotonic increasing instants, having the same number of elements of the `"coordinates"` value.
It does NOT allows a JSON `null` vlaue.
+
[width="99%", cols="1,^6,3", options="header"]
|=========
| Types   |      Formats of the `"datetimes"` value  |  _Comments_
| TimeInstant | [t1, t2, t3, ...]| _a list of monotonic increasing instants_
|=========

[NOTE]
==========
When the `"trs"` member has the default temporal CRS (i.e., ISO8601) object, an instant is generally encoded as a a JSON string of ISO 8601:2004 field-based formats using Z (e.g., 2016-09-11T06:10:32Z) or incremental time as the number of milliseconds since midnight (00:00 a.m.) on January 1, 1970 in UTC (e.g., 1465621816590), but others can be used such as:
-----
   YYYY (e.g., 1997)
   Year and month:
      YYYY-MM (e.g., 1997-07)
   Complete date:
      YYYY-MM-DD (e.g., 1997-07-16)
   Complete date plus hours and minutes:
      YYYY-MM-DDThh:mmTZD (e.g., 1997-07-16T19:20+01:00)
   Complete date plus hours, minutes and seconds:
      YYYY-MM-DDThh:mm:ssTZD (e.g., 1997-07-16T19:20:30+01:00)
   Complete date plus hours, minutes, seconds and a decimal fraction of a second
      YYYY-MM-DDThh:mm:ss.sTZD (e.g., 1997-07-16T19:20:30.450Z)
   where:
           YYYY = four-digit year
           MM   = two-digit month (01=January, etc.)
           DD   = two-digit day of month (01 through 31)
           hh   = two digits of hour (00 through 23) (am/pm NOT allowed)
           mm   = two digits of minute (00 through 59)
           ss   = two digits of second (00 through 59)
           s    = one or more digits representing a decimal fraction of a second
           TZD  = time zone designator (Z or +hh:mm or -hh:mm)
-----
==========

* `"orientations"`:  The `"orientations"` member is optional. Its value is a JSON array of sets of transformation matrices for rotating and scailing of the base representation of a member named `"geometry"`.
It allows a JSON `null` value. See <<geometry>> for a detailed expression of the transformation matrix. The combination of the `"geometry"` and `"orientations"` can represent a 3D temporal geometry of the MF_RigidTemporalGeometry type in ISO 19141.
* `"interpolation"`: The `"interpolation" member is mandatory, and its value is an GeometricInterpolation object (see <<interpolation>>). It does NOT allow a JSON `null` value.
Interpolation is a method of finding new values for any function using the given set of values. The unknown position at a particular point can be found using the GeometricInterpolation instance.

<<appendix-b1>> shows examples of TemporalPrimitiveGeometry instances.


[#taggregate, reftext='7.5. TemporalAggregateGeometry Object']
==== TemporalAggregateGeometry Object
When a TemporalGeometry object has a `"type"` member with one of the value of `"MultiMovingPoint"`, `"MultiMovingLineString"`, `"MultiMovingPolygon"`, and `"MovingGeometryCollection"`,
the object SHALL be a TemporalAggregateGeometry object with one additonal member named `"bundles"`.
The value of the `"bundles"` member is represented by a JSON array of a set of TemporalPrimitiveGeometry instances, having at least one instance.

[source, javascript]
{
    "type": "MultiMovingPoint | MultiMovingLineString | MultiMovingPolygon" | "MovingGeometryCollection",  // (MANDATORY) vbar | as a means to select ONE type.
    "bundles": [  //(MANDATORY)
        {
            "type": "MovingPoint | MovingLineString | MovingPolygon",  // (MANDATORY) vbar | as a means to select ONE type.
            "coordinates": [...],   //(MANDATORY)
            "datetimes" : [...],    //(MANDATORY)
            "orientations": [...], //(OPTIONAL)
            "interpolation": [...], //(MANDATORY)
        },
        ...
    ],
    "trs": {}, //(OPTIONAL)
    "crs": {}  //(OPTIONAL)
}

* *MultiMovingPoint*: An element of the "bundles" member SHALL be a JSON array of TemporalPrimitiveGeometry instances of type `"MovingPoint"`.
The leaf geometry at a time position must be an instance of type "MultiPoint" of GeoJSON, which is the union of each leaf of moving point members at the same time.
* *MultiMovingLineString*: An element of the "bundles" member SHALL be a JSON array of TemporalPrimitiveGeometry instances of type `"MovingLineString"`.
The leaf geometry at a time position must be an instance of type "MultiLineString" of GeoJSON, which is the union of each leaf of moving linestring members at the same time.
* *MultiMovingPolygon*: An element of the "bundles" member SHALL be a JSON array of TemporalPrimitiveGeometry instances of type `"MovingPolygon"`.
The leaf geometry at a time position must be an instance of type "MultiPolygon" of GeoJSON, which is the union of each leaf of moving polygon members at the same time.
* *MovingGeometryCollection*: Each element of "bundles" can be an TemporalPrimitiveGeometry with one of types of `"MovingPoint"`, `"MovingLineString"`, `"MovingPolygon"`, and `"MovingPointCloud"`.
The leaf geometry at a time position must be an instance of type `"GeometryCollection"` of GeoJSON, which is the union of each leaf of any temporal geometries at the same time.

<<appendix-b2>> shows examples of TemporalAggregateGeometry instances.



==== Requirement 2
Paragraph - intro text for the requirement.

Use the following table for Requirements, number sequentially.

include::requirements/requirement.adoc[]

Dictionary tables for requirements can be added as necessary. Modify the following example as needed.

[width="90%",options="header"]
|===
|Names |Definition |Data types and values |Multiplicity and use
|name 1 |definition of name 1 |float |One or more (mandatory)
|name 2 |definition of name 2 |character string type, not empty |Zero or one (optional)
|name 3 |definition of name 3 |GML:: Point PropertyType |One (mandatory)
|===
