[#crs, reftext='7.2.3']
==== CoordinateReferenceSystem Object
A coordinate reference system (CRS) is usually comprised of two components: one coordinate system and one datum (reference frame).
The IETF GeoJSON format recommends that the CRS for all GeoJSON coordinates is a geographic coordinate reference system,
using the World Geodetic System 1984 (WGS 84)<<WGS84>> datum, with longitude and latitude units of decimal degrees.
This is equivalent to the CRS identified by the http://www.epsg-registry.org/?display=entity&urn=urn:ogc:def:crs:EPSG::4326[EPSG:4326] with the axis Lat-Long.
For a 3D coordinate with an altitude/elevation value, the value refers to distance above mean sea level (MSL or AMSL).
However, a moving feature needs a temporal coordinate system and may be described by an engineering or parametric coordinates
in a certain application, such as robot or vessel navigation.
Therefore, MF-JSON Prism allows the `"crs"` member to describe an alternative CRS whose representation follows the way as described in GeoJSON-with-CRS<<GJSON2008>>.
Also it defines the `"trs"` member to describe a temporal CRS against which time is measured. A temporal CRS is always 1D with a temporal datum (origin) and its time unit.

* A non-null CoordinateReferenceSystem (CRS) object is a JSON object
with two mandatory members of the name `"type"` and `"properties"`.
* The value of the `"type"` member is a JSON string as one of the string `"Name"` and `"Link"`, indicating the type of CRS object.
* The value of the `"properties"` member is a JSON object with three optional members
named `"name"`, `"href"`, and `"type"` whose value is a JSON string or JSON `null` value.
* CRS shall not change coordinate ordering.

Depending on the value of `"type"`, there are three expressions: Named CRS, Linked CRS, and Default CRS.

===== 7.2.3.1. Named CRS
A Named CRS object indicates a coordinate reference system by name.
In this case, the value of its `"type"` member is the string `"Name"`.
The value of its `"properties"` member is a JSON object containing a `"name"` member
whose value is a string identifying a coordinate reference system (not JSON `null` value).
The value of `"href"` and `"type"` is a JSON `null` value.
This standard recommends an EPSG<<EPSG>> code as the value of `"name"`, such as "EPSG::4326."

[#namedcrs, reftext='{example-caption} {counter:example-num}']
.Example {example-num}: Example of a named CRS object
[source, javascript]
{
  "type": "Name",
  "properties": {
    "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
  }
}

===== 7.2.3.2. Linked CRS
A linked CRS object has one required member: `"href"` and one optional member: `"type"`.
The value of the required `"href"` member is a dereferenceable URI.
The value of the optional `"type"` member is a string that hints at the format
used to represent CRS parameters at the provided URI.
Suggested values are: `"Proj4"`, `"OGCWKT"`, `"ESRIWKT"`, but others can be used.

[#linkedcrs, reftext='{example-caption} {counter:example-num}']
.Example {example-num}: Example of a linked CRS object
[source, javascript]
{
  "type": "Link",
  "properties": {
    "href": "http://example.com/crs/42",
    "type": "Proj4"
  }
}

[#auxiliarycrs, reftext='{example-caption} {counter:example-num}']
.Example {example-num}: Example of a relative linked CRS object with an auxiliary file
[source, javascript]
{
  "type": "Link",
  "properties": {
    "href": "data.crs",
    "type": "OGCWKT"
  }
}

[#defaultcrs, reftext='7.2.3.3']
===== 7.2.3.3. Default CRS
MF-JSON Prism defines two default CRS objects for a spatial CRS and a temporal CRS as follows:

* http://www.opengis.net/def/crs/OGC/1.3/CRS84[WGS84] with longitude and latitude units of decimal degrees:
This CRS object is the default value of the `"crs"` member.

[source, javascript]
-----
    "crs" : {
        "type": "Name",
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        }
    }
-----

* http://www.iso.org/iso/home/standards/iso8601.htm[ISO8601] of dates and times using the Gregorian calendar and 24 hour local or Coordinated Universal Time (UTC):
This CRS object is the default value of the `"trs"` member.

[source, javascript]
-----
    "trs" : {
        "type": "Name",
        "properties": {
            "name": "urn:ogc:data:time:iso8601"
        }
    }
-----

A JSON `null` value of the `"crs"` and `"trs"` is considered as http://www.opengis.net/def/crs/OGC/1.3/CRS84[WGS84] and http://www.iso.org/iso/home/standards/iso8601.htm[ISO8601], respectively.

include::requirements/requirement_crs.adoc[]
