[appendix]
== (informative) Use Case examples

In the following two Use Cases are presented to illustrate possible application
scenarios of EO-WCS in the domain of earth observation and remote sensing.

=== Use Case 1

Provider offers, through an EO-WCS service, one Dataset Series containing Sea
Surface Temperature (SST) and another Dataset Series containing Ocean Color
(OC).

User wants to compare the timely development and distribution of some algal
bloom in relationship to ocean currents indicated by the changes in SST. User,
therefore, plans to analyze a timeseries of OC and SST imageries over a certain
period of time (TOI) in the Area of Interest (AOI).

User first addresses the EO-WCS service by issuing a _GetCapabilities_
request.The resulting response contains information about available
``DatasetSeriesId``s, their spatial extent (as ``WGS84BoundingBox``), as well as
their temporal validity (as `beginPosition` and ``endPosition``).

Based on this information, User can issue a _DescribeEOCoverageSet_ request,
using the received `DatasetSerieId` (as ``eoId``) to obtain detail information
on the content of the two offered DatasetSeries of interest. Since User is only
interested in a limited period of time and a certain area, the
_DescribeEOCoverageSet_ request contains parameters for spatial and temporal
subsetting, for example:

    subset=lat(32,47)&
    subset=long(11,33)&
    subset=phenomenonTime("2006-08-01","2006-08-22T19:22:00Z")

User will receive a response containing the ``CoverageId``s of the datasets
available within this spatio-temporal bounding box provided; notably, this set
will be empty if no item is contained within the area and time queried.

User subsequently decides about which of the coverages identified are of
interest and issues a _GetCoverage_ request for each `CoverageId` received in
the _DescribeEOCoverageSet_ response. Again, User can select an AOI (via the
subset parameter); additionally, specific bands (via range subsetting), output
coverage format, output CRS, interpolation method, etc. can be selected
depending on the WCS extensions implemented by the server; the Capabilities
document contains pertinent information. Following download via GetCoverage, the
SST and OC coverages can be analyzed and processed on User's local workstation.

=== Use Case 2

Provider offers, during harvesting seasons (e.g., March through August), three
2-monthly Stitched Mosaics for a certain area. Whenever new images are available
in this area they are included in the respective (time-slot) Stitched Mosaic,
possibly replacing older datasets or parts thereof. The providers applies a
"least cloud cover/newest on top" approach to feed into the respective mosaics.
At the end of each 2-month period the next mosaic is initiated. Stitched
Mosaics enable Provider to offer the full metadata set for each dataset
participating in a mosaic for any time instance, down to pixel-level accuracy.

User wants to assess crop yield for an AOI contained within the providers
Stitched Mosaics. For doing so, User needs data about the same AOI for at least
2 points in time. Further, User requires the full metadata recorded (including
possible lineage data) together with the actual imagery.

User addresses the EO-WCS by issuing a _GetCapabilities_ request.The response
contains the ``coverageId``s for all Stitched Mosaics available.

Further information - i.e., metadata - can be obtained through a
_DescribeCoverage_ request on the ``coverageId``s received. This yields bounding
box, footprint, bands, as well as timestamp information (e.g., oldest and
youngest image) of the datasets participating in the Stitched Mosaic.
Alternatively, if User needs details about those datasets comprising a
particular Stitched Mosaic, a _DescribeEOCoverageSet_ request using the
`CoverageId` as `eoId` can be issued. This results in detailed information
(time, footprint, bands, etc.) about each dataset participating in the object
queried.

For accessing the image data, User issues a _GetCoverage_ request providing the
identifier of the object to be retrieved. In addition to the mandatory request
parameters, further optional parameters allow specifying output format,
geographic subset, and further details; availability of this functionality
depends on the extensions the EO-WCS implements, as indicated in its
Capabilities document. The coverages retrieved finally can be analyzed and
processed further in User's local workstation environment.
